"""Domain models for dynamic one-time QR session and driver vehicle registration."""

from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field


class QRSessionStatus(str, Enum):
    """Lifecycle status of a one-time QR onboarding session."""

    ACTIVE = "active"
    SCANNED = "scanned"
    REGISTERED = "registered"
    EXPIRED = "expired"


class QRSession(BaseModel):
    """Dynamic single-use QR session generated by a charging station kiosk."""

    model_config = ConfigDict(frozen=True)

    session_id: str = Field(..., description="Unique cryptographically generated session ID")
    bay_id: str = Field(default="BAY-01", description="Charging bay / parking slot identifier")
    created_at: datetime = Field(..., description="Timestamp when QR was generated")
    status: QRSessionStatus = Field(default=QRSessionStatus.ACTIVE, description="Current session state")
    ev_id: Optional[str] = Field(default=None, description="Registered EV ID once claimed")
    expires_at: Optional[datetime] = Field(default=None, description="Expiration deadline for unused QR")


class EVRegistrationRequest(BaseModel):
    """Driver onboarding payload submitted from mobile phone upon scanning QR."""

    model_config = ConfigDict(frozen=True)

    session_id: str = Field(..., min_length=1, description="One-time session token from QR code")
    ev_id: Optional[str] = Field(default=None, description="Optional custom EV name / identifier")
    slot_id: Optional[str] = Field(default=None, description="Assigned parking/charging slot")
    battery_capacity_kwh: float = Field(default=60.0, gt=0.0, description="Battery capacity in kWh")
    soc_percent: float = Field(default=25.0, ge=0.0, le=100.0, description="Current State of Charge percentage")
    target_soc_percent: float = Field(default=85.0, ge=0.0, le=100.0, description="Target SoC percentage")
    max_charging_power_kw: float = Field(default=11.0, gt=0.0, description="Max vehicle charging rate in kW")
    departure_in_hours: float = Field(default=2.5, gt=0.0, description="Hours until planned departure")
